# 횡단보도 설치와 교통사고의 연관성
(가설 1) 가로등 설치가 많은 지역이 교통사고가 적다
(가설 2) 가로등 설치

In [1]:
import pandas as pd

street_lamp = pd.read_excel('../data/sp_street_lamp.xls', header=9, usecols='B, AD', encoding = 'utf-8')
street_lamp.rename(columns={street_lamp.columns[0]:'구별', street_lamp.columns[1]:'가로등'},inplace=True)
street_lamp


구별    가로등
0    종로구   9220
1     중구   8694
2    용산구   7248
3    성동구   5780
4    광진구   4774
5   동대문구   8149
6    중랑구   5729
7    성북구   5301
8    강북구   4525
9    도봉구   4471
10   노원구   9270
11   은평구   6428
12  서대문구   6075
13   마포구   8177
14   양천구   7833
15   강서구   6682
16   구로구   7490
17   금천구   5294
18  영등포구   9500
19   동작구   5568
20   관악구   4894
21   서초구  12691
22   강남구  14193
23   송파구  13263
24   강동구   7982

In [2]:
cross_walk = pd.read_excel('../data/sp_cross_walk.xlsx', header=1, usecols='B, C, D, E', encoding = 'utf-8')
cross_walk.drop([0], inplace=True)
cross_walk.rename(columns={cross_walk.columns[0]:'구별', 
                           cross_walk.columns[1]:'횡단보도',
                          },inplace=True)
cross_walk

구별  횡단보도  신호등있는횡단보도  신호등없는횡단보도
1    종로구   993        278        715
2     중구  1323        288       1035
3    용산구  1007        290        717
4    성동구  1136        319        817
5    광진구   963        258        705
6   동대문구  1264        398        866
7    중랑구  1317        396        921
8    성북구  1708        409       1299
9    강북구  1097        319        778
10   도봉구   942        321        621
11   노원구  1361        561        800
12   은평구  1334        438        896
13  서대문구  1086        272        814
14   마포구  1786        524       1262
15   양천구  1474        504        970
16   강서구  1814        567       1247
17   구로구  1575        432       1143
18   금천구   824        297        527
19  영등포구  1919        652       1267
20   동작구  1037        229        808
21   관악구   894        313        581
22   서초구  1887        484       1403
23   강남구  2606        594       2012
24   송파구  1829        613       1216
25   강동구  1484        438       1046

In [3]:
traffic_accident = pd.read_excel('../data/sp_traffic_accident.xls', header=1, usecols='B, D, E, C', encoding = 'utf-8')
traffic_accident.rename(columns={traffic_accident.columns[0]:'구별', traffic_accident.columns[1]:'발생건수',traffic_accident.columns[2]:'발생건수(만대당)', traffic_accident.columns[3]:'사망자수'},inplace=True)
traffic_accident

구별  발생건수  발생건수(만대당)  사망자수
0    종로구  1134      177.5     6
1     중구  1128      169.8     9
2    용산구  1330      142.2    14
3    성동구  1143       90.2     9
4    광진구  1108       93.2    10
5   동대문구  1699      139.2    14
6    중랑구  1565      113.2    10
7    성북구  1427       99.9    14
8    강북구  1216      122.6    13
9    도봉구   824       73.5     6
10   노원구  1569       93.1    14
11   은평구  1134       75.3    12
12  서대문구  1033      101.6     5
13   마포구  1671      123.7    11
14   양천구  1428       84.4    11
15   강서구  1502       67.4    11
16   구로구  1532       95.6    13
17   금천구   932       94.5     6
18  영등포구  2493      155.5    22
19   동작구  1412      117.2     9
20   관악구  1300       89.1     8
21   서초구  2478      126.9    18
22   강남구  3459      137.2    20
23   송파구  2860      111.9    27
24   강동구  1418       93.5    12

In [4]:
traffic_accident['사건당 사망자수']=traffic_accident['사망자수'] / traffic_accident['발생건수']
traffic_accident

구별  발생건수  발생건수(만대당)  사망자수  사건당 사망자수
0    종로구  1134      177.5     6  0.005291
1     중구  1128      169.8     9  0.007979
2    용산구  1330      142.2    14  0.010526
3    성동구  1143       90.2     9  0.007874
4    광진구  1108       93.2    10  0.009025
5   동대문구  1699      139.2    14  0.008240
6    중랑구  1565      113.2    10  0.006390
7    성북구  1427       99.9    14  0.009811
8    강북구  1216      122.6    13  0.010691
9    도봉구   824       73.5     6  0.007282
10   노원구  1569       93.1    14  0.008923
11   은평구  1134       75.3    12  0.010582
12  서대문구  1033      101.6     5  0.004840
13   마포구  1671      123.7    11  0.006583
14   양천구  1428       84.4    11  0.007703
15   강서구  1502       67.4    11  0.007324
16   구로구  1532       95.6    13  0.008486
17   금천구   932       94.5     6  0.006438
18  영등포구  2493      155.5    22  0.008825
19   동작구  1412      117.2     9  0.006374
20   관악구  1300       89.1     8  0.006154
21   서초구  2478      126.9    18  0.007264
22   강남구  3459      137.2    20  0.005782
23   송파구  2860      111.9    27  0.009441
24   강동구  1418       93.5    12  0.008463

In [5]:
car_speed = pd.read_excel('../data/sp_car_speed.xls', header=3, usecols='C, D', encoding = 'utf-8')
car_speed.rename(columns={car_speed.columns[0]:'구별', car_speed.columns[1]:'주행속도(km/h)'},inplace=True)
car_speed

구별  주행속도(km/h)
0    종로구        22.5
1     중구        19.5
2    용산구        26.6
3    성동구        25.0
4    광진구        25.1
5   동대문구        23.9
6    중랑구        22.8
7    성북구        24.6
8    강북구        21.3
9    도봉구        21.9
10   노원구        24.0
11   은평구        21.6
12  서대문구        23.6
13   마포구        24.5
14   양천구        25.4
15   강서구        23.6
16   구로구        23.6
17   금천구        23.5
18  영등포구        23.8
19   동작구        26.0
20   관악구        25.3
21   서초구        26.2
22   강남구        24.5
23   송파구        24.0
24   강동구        23.9

In [6]:
data_result = pd.merge(cross_walk ,traffic_accident, on='구별')
data_result

구별  횡단보도  신호등있는횡단보도  신호등없는횡단보도  발생건수  발생건수(만대당)  사망자수  사건당 사망자수
0    종로구   993        278        715  1134      177.5     6  0.005291
1     중구  1323        288       1035  1128      169.8     9  0.007979
2    용산구  1007        290        717  1330      142.2    14  0.010526
3    성동구  1136        319        817  1143       90.2     9  0.007874
4    광진구   963        258        705  1108       93.2    10  0.009025
5   동대문구  1264        398        866  1699      139.2    14  0.008240
6    중랑구  1317        396        921  1565      113.2    10  0.006390
7    성북구  1708        409       1299  1427       99.9    14  0.009811
8    강북구  1097        319        778  1216      122.6    13  0.010691
9    도봉구   942        321        621   824       73.5     6  0.007282
10   노원구  1361        561        800  1569       93.1    14  0.008923
11   은평구  1334        438        896  1134       75.3    12  0.010582
12  서대문구  1086        272        814  1033      101.6     5  0.004840
13   마포구  1786        524       1262  1671      123.7    11  0.006583
14   양천구  1474        504        970  1428       84.4    11  0.007703
15   강서구  1814        567       1247  1502       67.4    11  0.007324
16   구로구  1575        432       1143  1532       95.6    13  0.008486
17   금천구   824        297        527   932       94.5     6  0.006438
18  영등포구  1919        652       1267  2493      155.5    22  0.008825
19   동작구  1037        229        808  1412      117.2     9  0.006374
20   관악구   894        313        581  1300       89.1     8  0.006154
21   서초구  1887        484       1403  2478      126.9    18  0.007264
22   강남구  2606        594       2012  3459      137.2    20  0.005782
23   송파구  1829        613       1216  2860      111.9    27  0.009441
24   강동구  1484        438       1046  1418       93.5    12  0.008463

In [7]:
data2_result = pd.merge(data_result ,car_speed, on='구별')
data2_result

구별  횡단보도  신호등있는횡단보도  신호등없는횡단보도  발생건수  발생건수(만대당)  사망자수  사건당 사망자수  \
0    종로구   993        278        715  1134      177.5     6  0.005291   
1     중구  1323        288       1035  1128      169.8     9  0.007979   
2    용산구  1007        290        717  1330      142.2    14  0.010526   
3    성동구  1136        319        817  1143       90.2     9  0.007874   
4    광진구   963        258        705  1108       93.2    10  0.009025   
5   동대문구  1264        398        866  1699      139.2    14  0.008240   
6    중랑구  1317        396        921  1565      113.2    10  0.006390   
7    성북구  1708        409       1299  1427       99.9    14  0.009811   
8    강북구  1097        319        778  1216      122.6    13  0.010691   
9    도봉구   942        321        621   824       73.5     6  0.007282   
10   노원구  1361        561        800  1569       93.1    14  0.008923   
11   은평구  1334        438        896  1134       75.3    12  0.010582   
12  서대문구  1086        272        814  1033      101.6     5  0.004840   
13   마포구  1786        524       1262  1671      123.7    11  0.006583   
14   양천구  1474        504        970  1428       84.4    11  0.007703   
15   강서구  1814        567       1247  1502       67.4    11  0.007324   
16   구로구  1575        432       1143  1532       95.6    13  0.008486   
17   금천구   824        297        527   932       94.5     6  0.006438   
18  영등포구  1919        652       1267  2493      155.5    22  0.008825   
19   동작구  1037        229        808  1412      117.2     9  0.006374   
20   관악구   894        313        581  1300       89.1     8  0.006154   
21   서초구  1887        484       1403  2478      126.9    18  0.007264   
22   강남구  2606        594       2012  3459      137.2    20  0.005782   
23   송파구  1829        613       1216  2860      111.9    27  0.009441   
24   강동구  1484        438       1046  1418       93.5    12  0.008463   

    주행속도(km/h)  
0         22.5  
1         19.5  
2         26.6  
3         25.0  
4         25.1  
5         23.9  
6         22.8  
7         24.6  
8         21.3  
9         21.9  
10        24.0  
11        21.6  
12        23.6  
13        24.5  
14        25.4  
15        23.6  
16        23.6  
17        23.5  
18        23.8  
19        26.0  
20        25.3  
21        26.2  
22        24.5  
23        24.0  
24        23.9

In [8]:
import numpy as np
#np.corrcoef(data2_result['가로등'],data2_result['발생건수'])

In [9]:
#np.corrcoef(data2_result['가로등'],data2_result['발생건수(만대당)'])

In [10]:
#np.corrcoef(data2_result['가로등'],data2_result['사망자수'])

In [11]:
#np.corrcoef(data2_result['가로등'],data2_result['사건당 사망자수'])

In [12]:
#np.corrcoef(data2_result['가로등'],data2_result['주행속도(km/h)'])

In [13]:
np.corrcoef(data2_result['주행속도(km/h)'],data2_result['발생건수'])

array([[1.        , 0.28505964],
       [0.28505964, 1.        ]])

In [14]:
np.corrcoef(data2_result['주행속도(km/h)'],data2_result['횡단보도'])

array([[1.        , 0.12207743],
       [0.12207743, 1.        ]])

In [15]:
np.corrcoef(data2_result['주행속도(km/h)'],data2_result['신호등있는횡단보도'])

array([[1.        , 0.10074315],
       [0.10074315, 1.        ]])

In [16]:
np.corrcoef(data2_result['주행속도(km/h)'],data2_result['신호등없는횡단보도'])

array([[1.        , 0.12018863],
       [0.12018863, 1.        ]])

In [17]:
np.corrcoef(data2_result['사망자수'],data2_result['주행속도(km/h)'])

array([[1.       , 0.2161617],
       [0.2161617, 1.       ]])

In [18]:
np.corrcoef(data2_result['사망자수'],data2_result['횡단보도'])

array([[1.        , 0.72794174],
       [0.72794174, 1.        ]])

In [19]:
np.corrcoef(data2_result['사망자수'],data2_result['신호등있는횡단보도'])

array([[1.       , 0.7540019],
       [0.7540019, 1.       ]])

In [20]:
np.corrcoef(data2_result['사망자수'],data2_result['신호등없는횡단보도'])

array([[1.        , 0.65767803],
       [0.65767803, 1.        ]])

In [21]:
np.corrcoef(data2_result['사망자수'],data2_result['발생건수(만대당)'])

array([[1.        , 0.23154245],
       [0.23154245, 1.        ]])

In [22]:
np.corrcoef(data2_result['발생건수'],data2_result['횡단보도'])

array([[1.        , 0.85600206],
       [0.85600206, 1.        ]])

In [23]:
np.corrcoef(data2_result['발생건수'],data2_result['신호등있는횡단보도'])

array([[1.        , 0.74660228],
       [0.74660228, 1.        ]])

In [24]:
np.corrcoef(data2_result['발생건수'],data2_result['신호등없는횡단보도'])

array([[1.       , 0.8272853],
       [0.8272853, 1.       ]])

In [25]:
data2_result.to_csv('../data/sp. data2_result_gu_name.csv',
                        sep=',',
                        encoding='utf-8')

In [26]:
import matplotlib.pyplot as plt
%matplotlib inline
import pandas as pd
import seaborn as sns
import folium
import googlemaps
gmaps_key = "AIzaSyDma2vIQ4kFgB8xY1BeLmjwHH3r7Iz7RdA" # google maps api 키!
gmaps = googlemaps.Client(key=gmaps_key)

In [35]:
data2_result
data2_result_anal_raw = pd.read_csv('../data/sp. data2_result_gu_name.csv',
                            encoding='utf-8',
                            index_col=0)
data2_result_anal = pd.pivot_table(data2_result_anal_raw, index='구별', aggfunc=np.sum)
data2_result_anal.head()

발생건수  발생건수(만대당)  사건당 사망자수  사망자수  신호등없는횡단보도  신호등있는횡단보도  주행속도(km/h)  횡단보도
구별                                                                          
강남구  3459      137.2  0.005782    20       2012        594        24.5  2606
강동구  1418       93.5  0.008463    12       1046        438        23.9  1484
강북구  1216      122.6  0.010691    13        778        319        21.3  1097
강서구  1502       67.4  0.007324    11       1247        567        23.6  1814
관악구  1300       89.1  0.006154     8        581        313        25.3   894

In [36]:
data2_result_anal_raw

구별  횡단보도  신호등있는횡단보도  신호등없는횡단보도  발생건수  발생건수(만대당)  사망자수  사건당 사망자수  \
0    종로구   993        278        715  1134      177.5     6  0.005291   
1     중구  1323        288       1035  1128      169.8     9  0.007979   
2    용산구  1007        290        717  1330      142.2    14  0.010526   
3    성동구  1136        319        817  1143       90.2     9  0.007874   
4    광진구   963        258        705  1108       93.2    10  0.009025   
5   동대문구  1264        398        866  1699      139.2    14  0.008240   
6    중랑구  1317        396        921  1565      113.2    10  0.006390   
7    성북구  1708        409       1299  1427       99.9    14  0.009811   
8    강북구  1097        319        778  1216      122.6    13  0.010691   
9    도봉구   942        321        621   824       73.5     6  0.007282   
10   노원구  1361        561        800  1569       93.1    14  0.008923   
11   은평구  1334        438        896  1134       75.3    12  0.010582   
12  서대문구  1086        272        814  1033      101.6     5  0.004840   
13   마포구  1786        524       1262  1671      123.7    11  0.006583   
14   양천구  1474        504        970  1428       84.4    11  0.007703   
15   강서구  1814        567       1247  1502       67.4    11  0.007324   
16   구로구  1575        432       1143  1532       95.6    13  0.008486   
17   금천구   824        297        527   932       94.5     6  0.006438   
18  영등포구  1919        652       1267  2493      155.5    22  0.008825   
19   동작구  1037        229        808  1412      117.2     9  0.006374   
20   관악구   894        313        581  1300       89.1     8  0.006154   
21   서초구  1887        484       1403  2478      126.9    18  0.007264   
22   강남구  2606        594       2012  3459      137.2    20  0.005782   
23   송파구  1829        613       1216  2860      111.9    27  0.009441   
24   강동구  1484        438       1046  1418       93.5    12  0.008463   

    주행속도(km/h)  
0         22.5  
1         19.5  
2         26.6  
3         25.0  
4         25.1  
5         23.9  
6         22.8  
7         24.6  
8         21.3  
9         21.9  
10        24.0  
11        21.6  
12        23.6  
13        24.5  
14        25.4  
15        23.6  
16        23.6  
17        23.5  
18        23.8  
19        26.0  
20        25.3  
21        26.2  
22        24.5  
23        24.0  
24        23.9

In [37]:
data2_result_sort = data2_result.sort_values(by='발생건수',ascending=False)
data2_result.head()

구별  횡단보도  신호등있는횡단보도  신호등없는횡단보도  발생건수  발생건수(만대당)  사망자수  사건당 사망자수  \
0  종로구   993        278        715  1134      177.5     6  0.005291   
1   중구  1323        288       1035  1128      169.8     9  0.007979   
2  용산구  1007        290        717  1330      142.2    14  0.010526   
3  성동구  1136        319        817  1143       90.2     9  0.007874   
4  광진구   963        258        705  1108       93.2    10  0.009025   

   주행속도(km/h)  
0        22.5  
1        19.5  
2        26.6  
3        25.0  
4        25.1

In [38]:
## 서울시 범죄율에 대한 지도 시각화
import json
geo_path='../data/02. skorea_municipalities_geo_simple.json'
geo_str=json.load(open(geo_path, encoding='utf-8'))

In [39]:
columns=[data2_result.index, data2_result['발생건수']]
columns
map2=folium.Map([37.5002,126.982],zoom_start=11,
              tiles='stamen toner')

map2.choropleth(geo_data=geo_str,
              data=data2_result_anal['발생건수'],
              columns=[data2_result.index, data2_result['발생건수']],
              fill_color='YlGn',
              key_on='feature.id')
map2
